name: Create Azure resources

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep template
        run: |
          az deployment group create \
            --resource-group ${{ env.AZURE_RG }} \
            --template-file ./config/main.bicep \
            --parameters namePrefix=${{ env.AZURE_PREFIX }}
    env:
      AZURE_RG: ${{ vars.AZURE_RG }}
      AZURE_PREFIX: ${{ vars.AZURE_PREFIX }}
