name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/setup-azurecli@v1
        with:
          version: 'latest'

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.AZURE_PREFIX }}acr.azurecr.io/${{ secrets.AZURE_PREFIX }}containerapp:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.AZURE_PREFIX }}acr.azurecr.io/${{ secrets.AZURE_PREFIX }}containerapp:latest

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
            --name ${{ secrets.AZURE_PREFIX }}containerapp \
            --resource-group pets-workshop \
            --image ${{ secrets.AZURE_PREFIX }}acr.azurecr.io/${{ secrets.AZURE_PREFIX }}containerapp:latest \
            --cpu 0.5 \
            --memory 1.0Gi
